begin;
create extension if not exists pgtap with schema extensions;
select plan(18);
insert into auth.users(id) values('00000000-0000-0000-0000-000000000101'),('00000000-0000-0000-0000-000000000102');
create temporary table fixture as select jsonb_object_agg(key,'A*'::text) as rankings from unnest(array['bakerloo','central','circle','district','elizabeth','hammersmith-city','jubilee','metropolitan','northern','piccadilly','victoria','waterloo-city','overground','dlr','trams','thameslink','cable-car','uber-boat','heathrow-express']) as key;
grant select on fixture to anon,authenticated;
select ok(public.valid_tube_rankings((select rankings from fixture)), 'Complete rankings accepted');
select is(public.valid_tube_rankings('{}'::jsonb),false,'Empty ranking rejected');
select is(public.valid_tube_rankings((select rankings - 'central' from fixture)),false,'Missing line rejected');
select is(public.valid_tube_rankings((select rankings || '{"central":"S"}'::jsonb from fixture)),false,'Unknown tier rejected');
select is(public.valid_tube_rankings((select rankings || '{"fake":"A*"}'::jsonb from fixture)),false,'Extra line rejected');
select is(public.valid_tube_rankings('[]'::jsonb),false,'Array rejected');
set local role anon;
select throws_ok($$ select public.submit_ranking('Imposter',(select rankings from fixture)) $$,'42501',null,'Unauthenticated callers cannot submit');
select throws_ok($$ insert into public.submissions(user_id,username,rankings) values('00000000-0000-0000-0000-000000000101','Imposter',(select rankings from fixture)) $$,'42501',null,'Direct anonymous insert denied');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-000000000101","role":"authenticated"}',true);
set local role authenticated;
select lives_ok($$ select public.submit_ranking('Alice',(select rankings from fixture)) $$,'Anonymous identity can submit');
select throws_ok($$ select public.submit_ranking('Alice',(select rankings from fixture)) $$,'P0001',null,'Repeat updates are rate limited');
select throws_ok($$ update public.submissions set username='Hijacked' $$,'42501',null,'Direct update cannot bypass guarded function');
select throws_ok($$ delete from public.submissions $$,'42501',null,'Clients cannot delete submissions');
select throws_ok($$ select user_id from public.submissions $$,'42501',null,'Session identities are private');
reset role;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-000000000102","role":"authenticated"}',true);
set local role authenticated;
select lives_ok($$ select public.submit_ranking('Alice',(select jsonb_object_agg(key,'F'::text) from jsonb_each((select rankings from fixture)))) $$,'Same name with another identity creates its own vote');
select is((select count(*) from public.submissions where username='Alice'),2::bigint,'Names cannot claim another identity');
set local role anon;
select is((select count(*) from public.submissions),2::bigint,'Public visitors can read both submissions');
select is((select average_score from public.community_averages() where line_id='central'),3::numeric,'Average includes both opposite votes');
select is((select count(*) from public.community_averages()),19::bigint,'All 19 services have an average');
reset role;
select * from finish();
rollback;
